### ISSUE TITLE
win32a problem building with MinGW

### ISSUE THREAD

**Issue by BigRedEye** [Bill-Gray/PDCurses#10]
Hi!
I try to build PDCurses using MinGW, but have a problem in the second file which is specific for win32a:

` GLYPHSET *PDC_unicode_range_data = NULL;`
` ^`
`../win32a/pdcdisp.c: In function 'character_is_in_font':`
`../win32a/pdcdisp.c:462:5: error: unknown type name 'WCRANGE'`
`     WCRANGE *wptr = PDC_unicode_range_data->ranges;`
`     ^`
`../win32a/pdcdisp.c:462:43: error: request for member 'ranges' in something not a structure or union`
`     WCRANGE *wptr = PDC_unicode_range_data->ranges;`
`                                           ^`
`../win32a/pdcdisp.c:469:36: error: request for member 'cRanges' in something not a structure or union`
`     for( i = PDC_unicode_range_data->cRanges; i; i--, wptr++)`
`.                                   ^`
`../win32a/pdcdisp.c:470:15: error: request for member 'wcLow' in something not a structure or union`
`       if( wptr->wcLow > ichar)`
`               ^`
`../win32a/pdcdisp.c:472:20: error: request for member 'wcLow' in something not a structure or union`
`       else if( wptr->wcLow + wptr->cGlyphs > ichar)`
`                    ^`
`../win32a/pdcdisp.c:472:34: error: request for member 'cGlyphs' in something not a structure or union`
`       else if( wptr->wcLow + wptr->cGlyphs > ichar)`
`                                  ^`
`mingwin32.mak:147: recipe for target 'pdcdisp.o' failed`
`mingw32-make: *** [pdcdisp.o] Error 1`

 I have already reinstall MinGW, but the problem is the same. So likely problem isn't mine.
Also, win32 builds without problems. I really need win32a flavour for my rpg. Can you help me?

**Comment by Bill-Gray** [comment]
Thanks for mentioning this.  I've heard from a couple of other people
who ran into this issue,  so I have a quick answer:   edit win32a/pdcwin.h,
and look for the following comment near the top :

#ifdef PDC_WIDE
# define UNICODE
# define _UNICODE
      /* We only need the 'fallback font' for the wide-char version, */
      /* and it'll only work in Win2000 or later (earlier versions   */
      /* lack the necessary functions from the Win32 API).  Comment  */
      /* out the following line if you're dealing with a really old  */
      /* system,  or just don't want to use a fallback font.         */
#define USE_FALLBACK_FONT
#endif

    So comment out USE_FALLBACK_FONT,  and you should be all set.  You
will,  of course,  lose the fallback font capability.  The fallback
font is handy for avoiding mojibake (ensuring that almost all Unicode
characters are displayed correctly,  even if they aren't available
in your current font) :

http://projectpluto.com/win32a.htm#fallback_font

    ...but it's not essential,  and (as you found) not always supported.

    A better solution would be to say something like

#if !typedeffed( GLYPHSET) || !typedeffed( WCRANGE)
    #undefine USE_FALLBACK_FONT
#endif

    ...that is,  "if you can't use the fallback font anyway,  don't
try to use it."   Except that (as best I can tell) there is no way to
determine if something is typedeffed,  as opposed to plain old #defined.
I may give another try to figuring out how to get that to work...

-- Bill

**Comment by BigRedEye** [comment]
Thanks! It helps me:) I am very grateful to your response
