### ISSUE TITLE
pdcurses.rc + pdcurses.ico missing in vt flavor, otherwise duplicated

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#107]
I'd vote to move them from osdir to srcdir and could provide a PR for this.
Additional pdcurses.rc should use the version numbers defined in curses.h

**Comment by GitMensch** [comment]
ping @Bill-Gray

**Comment by GitMensch** [comment]
@Bill-Gray this is solved with the new https://github.com/Bill-Gray/PDCurses/tree/master/common directory, isn't it?

**Comment by Bill-Gray** [comment]
(Quick check) Yup.  pdcurses.ico is completely gone now,  and pdcurses.rc is in 'common' (both following @wmcbrine).  So this is an ex-issue.
