### ISSUE TITLE
No README for Win32a port

### ISSUE THREAD

**Issue by yonnig** [Bill-Gray/PDCurses#11]
Got a 404 error when clicking on the "Win32a" link of the main help page.

**Comment by Bill-Gray** [comment]
Thank you.  I made a goof here.  All flavors of PDCurses had README files,
which were modified to make README.md files,  except for Win32a.  I've fixed
this,  and brought the Win32a (and console Win32) Readmes up to date :

https://github.com/Bill-Gray/PDCurses/commit/f5821318e0f16ea45af94aad29d5736cbe0f2ac4

    So it should all work correctly now...

**Comment by GitMensch** [comment]
It does for me - can be closed.
