### ISSUE TITLE
Different colored diacritical marks in WinGUI?

### ISSUE THREAD

**Issue by sigmareaver** [Bill-Gray/PDCurses#115]
I was just doing some testing on the 'newtest' demo and trying to change the color between the base characters and diacritical marks, but I didn't have any luck so I'm guessing that it's not possible? How difficult would it be to allow diacritical marks to be uniquely colored?

**Comment by Bill-Gray** [comment]
Sorry for late reply here!
I assume you mean something like "I want to show é with the accent mark in red,  the 'e' in green,  and the background in blue"?  I don't see a way to do that.  The Curses color model works with color _pairs_,  not triplets;  you can select,  for a given character cell,  a foreground and a background color index.  There's no way to specify a third color.

**Comment by GitMensch** [comment]
Yes, that was what @sigmareaver asked.
@Bill-Gray do you see an option to add this with UTF8 combined characters (= both have a separate "character" and are only combined during display) in WinGUI? If not the only option to would add support for this curses extension in upstream, so if at all this should be raised in https://github.com/wmcbrine/PDCurses/issues (and closed here), correct?

**Comment by Bill-Gray** [comment]
I'd briefly had the thought this might be possible,  though can't say I'd be strongly inclined to do it.  However,  I think I have a perfect excuse for not doing it,  namely : you can't do it.
There are two platforms (WinGUI and VT) that support combining characters.  I think X11 and WinCon could;  dunno if SDLx is that advanced.  On the platforms we now have (and I would bet X11 and WinCon),  you cannot say "draw e and then the accent,  changing the color in between".  One glyph influences the other.  You supply them as a combined unit,  and the font rendering code then figures out what they look like when displayed together.
@sigmareaver,  I probably ought to have started out by asking why you'd want to do this?  If you're just looking for a way to,  say,  put red marks over or under certain characters,  I'd suggest giving them the `A_UNDERLINE` or `A_OVERLINE` attribute and then using `set_line_color(COLOR_RED)`.  Or,  alternatively,  maybe setting the background color to help that text stand out.  Or something like that.

**Comment by sigmareaver** [comment]
Ah, just to answer your question, it was for an ASCII style game. You know, stuff like Dwarf Fortress. Though I prefer the simplicity of C and consoles, it seems like the way to go may be a game engine and a shader that renders characters.

**Comment by sigmareaver** [comment]
Ah, just to answer your question, it was for an ASCII style game. You know, stuff like Dwarf Fortress. Since I had a lot of experience with MUD game environments, I was preferring C and text, but it seems like the way to go may be a game engine and a shader that renders characters.

**Comment by GitMensch** [comment]
While this is unrelated - if you have enough place (effectively 2 rows) then you could split the characters [especially with the UTF8 or wide variant] leaving the lower for the characters and the upper one, with a different color-pair for the diacritical marks (not using the accent but the ["BELOW" diacritical marks](https://cloford.com/resources/charcodes/utf-8_diacritical-marks.htm)).
