### ISSUE TITLE
folder "docs" missing?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#118]
I found the old directory be renamed to "man", but the new upstream docs directory seems to be missing?

**Comment by Bill-Gray** [comment]
Thank you.  I'd noticed that,  but hadn't actually got round to moving that over.
Looks as if everything that was in 'man' is now either in 'docs',  or some other folder,  or is obsolete.  I've deleted 'man',  copied William's 'docs',  and modified HISTORY.md to describe the combined and convoluted history of our diverged,  and now "merged" (*),  forks.
(*) The code is,  for practical purposes,  merged.  If past experience is a guide,  maybe 10% of it will actually make it into the wmcbrine version.  But any code written for that version should compile and run with this version.

**Comment by GitMensch** [comment]
That's nice, thank you. Note: the commit saying "removed man" did only removed part of its content, not the folder.
