### ISSUE TITLE
Travis state broken

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#122]
https://travis-ci.com/github/Bill-Gray/PDCurses reports:

>  This is not an active repository  
Please contact the admin to enable it or to receive admin rights yourself. 

The builds itself are fine - @Bill-Gray can you please check what to "enable" there?

**Comment by Bill-Gray** [comment]
Enabled and building correctly.

**Comment by GitMensch** [comment]
Works fine in all places but at least the hook for PRs is missing, the auto-checks should include Travis, for example with the last one one could not know from the check state if SDL still builds or not (it does of course but "this repo" only knew after the merge).
@Bill-Gray can you check if there's an option to enable that somewhere, please [only related: can the GitHub CI build more than vt]?
