### ISSUE TITLE
Attributes not working on... something

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCurses#129]
A continuation of [this discussion on the GnuCOBOL group](https://sourceforge.net/p/open-cobol/discussion/help/thread/bc0f3d2ea5/).  Despite the name of the thread,  the colors appear to be fine;  it's just that none of the attributes (standout,  reverse,  blink) have any effect.  Note,  for example,  that in [the screenshot of David Wall's 3.9 result](https://sourceforge.net/p/open-cobol/discussion/help/thread/bc0f3d2ea5/b8dc/a568/72df/9231/attachment/PDC3.9.jpg),  each attribute has some expected effect.  In [his 4.2 result](https://sourceforge.net/p/open-cobol/discussion/help/thread/bc0f3d2ea5/b8dc/a568/72df/9231/attachment/PDC4.2.jpg),  the 'normal' colors look as they did in the 3.9 version;  but they don't change as attributes are applied.  The attributes appear to be simply ignored.

I've tried to replicate this,  without success thus far.  We do not (to my knowledge) have a simple bit of code where this fails;  it _could_ be a GnuCOBOL issue.  (Though enough has changed in PDCurses since 3.9 to make it worth raising as an issue here.)

**Comment by GitMensch** [comment]
Just one note from a later update:

> Specifically 4.1.1 & CHTYPE=64 - obviously the colours are different (or non existant) in the CHTYPE=32 version of 4.1.1 or 4.2.

So the summarized report is that using color pairs that use the default constants and then applying the attributes on it (which worked since years) only works with CHTYPE=64.

The code in GnuCOBOL that produces the colors is found in [screenio.c, lines 235-313](https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnucobol-3.x/libcob/screenio.c#l235) and uses the exact same code (verified with comparing the preprocessing).

The styles are applied in [`cob_screen_attr(), screenio.c:320-355`](https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnucobol-3.x/libcob/screenio.c#l320).

`A_REVERSE` translates to `(chtype)0x00200000` vs. `((chtype)0x020 << 21)`.

As it works with 64bit chtypes but not with 32bit I guess there's some "cut" somewhere or some place in PDCurses only uses the 64bit chtypes... checking the differences between 3.9 and 4.2 show a difference in the 32bit chtypes:

```c
#ifdef PDC_WIDE
    # define A_CHARTEXT   (chtype)0x0000ffff
    # define A_ATTRIBUTES (chtype)0xffff0000
    # define A_DIM        A_NORMAL
    # define A_OVERLINE   A_NORMAL
    # define A_STRIKEOUT  A_NORMAL
#else          /* with 8-bit chars,  we have bits for these attribs : */
    # define A_CHARTEXT   (chtype)0x000000ff
    # define A_ATTRIBUTES (chtype)0xffffe000
    # define A_DIM        (chtype)0x00008000
    # define A_OVERLINE   (chtype)0x00004000
    # define A_STRIKEOUT  (chtype)0x00002000
#endif
```

the part after `PDC_WIDE` is exactly the same definition as with 3.9, the different set (which seems to be active in the report) is 4.x chtype32 non-wide only.... but the defined attributes are 100% identical, this at least _looks_ suspicious.

**Comment by Bill-Gray** [comment]
I've got some test code now to try this out,  and... I'm not replicating the bug.  Probably haven't hit the right combination yet.  Or my code may not be doing something that yours does.  I've tried 32-bit `chtype`s with WinCon and WinGUI,  both wide-character and 8-bit mode,  compiling with MinGW and with MSVC.  It keeps working in all combos.

Are the failures you're seeing with all 32-bit `chtype` builds?  Just with wide-character builds?  Is this a WinCon issue or a general PDCurses issue (i.e.,  do you see the same thing with the VT or X11 or WinGUI platforms)?  Do you have a minimal test case that doesn't involve all of GnuCOBOL to see it?  (Speaking of which... [here's my test code](https://www.projectpluto.com/temp/test_col.c).  Sets up a similar display of all combos of eight foreground with eight background colors and with reverse,  standout,  and blinking flavors.)

The attributes you quote from `curses.h` look reasonable to me.  In either wide-character or 8-bit mode,  we have access to the upper 16 bits and treat them identically (which is why the color macros and defined attributes are,  as you note,  identical).  In 8-bit mode,  we've freed up eight bits and use three of them for `A_DIM`, `A_OVERLINE`,  and `A_STANDOUT`;  in wide-char mode,  we don't have room for those attributes and they're unavailable.

**Comment by GitMensch** [comment]
Thank you for the explanation of the 8bit modes + attributes.

I gave your test program a try with wincon - there are no colors at all, I guess that shows that something is broken?

```sh
pushd /d/dev/PDCurses-4.2.0-beta/wincon
mdkir build_msys && cd build_msys
make -f ../Makefile.mng UTF8=N WIDE=N CHTYPE_32=Y INFOEX=N PDCURSES_SRCDIR=../..
gcc ../test_col.c -I ../.. pdcurses.a
./a.exe
```

results in the following: 
![black'n'white](https://user-images.githubusercontent.com/6699539/82789637-eab9f980-9e6a-11ea-81df-064d3824b93f.png)

... this applies to every test program, too - all are black'n'white...

Tried the exact same procedure with 3.9 -> not possible because there is no Makefile.mng any more (we only have this with wingui + wincon, possibly something to clean up), adjusted to use the plain Makefile, built, demos have colors. There's definitely something broken in PDCurses 4.2 here.
What to do next?

**Comment by Bill-Gray** [comment]
I'm not surprised that _this_ procedure failed...
```
make -f ../Makefile.mng UTF8=N WIDE=N CHTYPE_32=Y INFOEX=N PDCURSES_SRCDIR=../..
gcc ../test_col.c -I ../.. pdcurses.a
```
...because the library was compiled with 32-bit `chtype`s and `test_col` was compiled with (default) 64-bit `chtype`s.  Actually,  I'm just surprised that it ran at all.  (Just tried it with VT, and got results matching yours.  Recompiling `test_col.c` with `-DCHTYPE_32` got correct results.)
I assume that's not the whole thing,  though,  because you say _all_ tests failed.  And those were presumably compiled when you did the first make,  and _did_ build with 32-bit chtypes. (True?)  I think if you did compile `test_col.c` with matching flags,  you'd either see it working correctly (as shown in your screenshot with the 64-bit build) or incorrectly (with the first eight lines replicated eight times,  the way David Wall saw them.)
Good to know it's not just a WinCon thing.  That's really William's code;  if the error was in there,  I'd be at a serious disadvantage in trying to debug it.  If the bug affects all flavors,  it narrows down the scope considerably.

**Comment by GitMensch** [comment]
The initial demo results (all black'n'white) were solved by recompiling, I've possibly did not `make clear` first. If I add `-DCHTYPE_32` I get the following results using the vt port:

GNU/Linux on wsl1:
![no blink](https://user-images.githubusercontent.com/6699539/82821854-13f77b80-9ea5-11ea-98fc-54b0a0fe9e68.png)

colors fine, blink attribute has no effect

MSYS:
![color.only some lines](https://user-images.githubusercontent.com/6699539/82821626-bb27e300-9ea4-11ea-98f7-fc6b4c272031.png)
colors fine, but only a partial output "over" existing text

... and that is wincon with correct CHTYPE set:
![colors!](https://user-images.githubusercontent.com/6699539/82822127-89fbe280-9ea5-11ea-915e-26225f2a47e4.png)
colors fine, blink attribute has no effect

So, from these: should we investigate the missing lines and/or "overwrite" on vt+msys? All other seem fine (there's no blink support with CHTYPE_32, I guess).

**Comment by Bill-Gray** [comment]
By default,  `A_BLINK` doesn't blink;  it just intensifies colors.  You have to call `PDC_set_blink(TRUE);` to get actual blinking text.

I assume the reason is that "real" blinking text is widely scorned.  The general thinking is that it should only be used when you _really_ need someone's attention ("the nuclear reactor is about to melt down").  Otherwise,  the intensified colors should be good enough as an attention-getter.

I've [posted an updated `test_col.c` with an option to show actually blinking text.](https://www.projectpluto.com/temp/test_col.c) It also fixes a bug where I used `& 3` where it should have been `& 4`,  and I realized that I'd cut-and-pasted comments from a previous bit of test code (one used to explore default coloring.)

Run the new version as `test_col 1`,  and bold text will be shown as actually bold.  `test_col 2` gets actually blinking text.  `test_col 3` gets both.  Plain `test_col` (or `test_col 0`) results in default text (neither `PDC_set_blink()` nor `PDC_set_bold()` is called.)

**Comment by GitMensch** [comment]
I guess the not matching flags is likely what resulted in the "not working" issue - if you use anything but the default one (which is the reason that CHTYPE_64 works) and not add it to the `CPPFLAGS` then you're lost.
I see only one solution to this (which will also solve it "forever"): create [pd]curses.h from curses.h.in during make with defines for CHTYPE, WIDE and UTF8 as requested. What do you think?

**Comment by DCWall** [comment]
Any advance on where we are on this ?? -  I must admit - I'd rather something was 'fixed' in the actual distributed source rather than US having to patch any distribution before building.
(US being the great unwashed - so to speak).
All the best to all who read & keep safe - David Wall.

**Comment by Bill-Gray** [comment]
As far as I know,  it _is_ fixed in the distributed source.  Unless I'm misunderstanding,  the problems arise when PDCurses is compiled with one set of flags and the application with a different set.  Only "fix" for that,  at least at present,  is to make sure that the same chtype size,  wide vs. ASCII,  and UTF8 settings are used for all compilation.
Do you think you're getting a color issue even with all compilation flags matching?

**Comment by DCWall** [comment]
Sorry Bill,  I 'jumped' in head-first before thinking - I got the wrong impression - in that I 'thought' we had to make a patch (slightly different configure) to PDC before things would work. This was NOT the case - PDCurses gets built as normal (however we want) - THEN - The application is what needs to be configured the same way. Sorry mate - mea culpa. (You can delete these if you want).  DW.

**Comment by Bill-Gray** [comment]
Hi David,
No worries... we _have_ had an issue or two with color regressions over the years,  and I was entirely ready to believe we had another one.
It sounds as if I should close this as 'fixed'.  @GitMensch has suggested we build a `pdcurses.h` with predefined `chtype` and wide and UTF8 attributes,  but (a) that's a bit outside of the stated issue and (b) we seem to be having assorted ideas as to how to tackle the problem anyway;  I'm inclined to let the thinking marinate and _then_ decide/write code.

**Comment by GitMensch** [comment]
> So, from these: should we investigate the missing lines and/or "overwrite" on vt+msys? All other seem fine (there's no blink support with CHTYPE_32, I guess).

Ping @Bill-Gray

**Comment by Bill-Gray** [comment]
In re missing lines : when the VT flavor runs on *nix,  it gets the initial screen size using `termios` functions... which we don't have in Windows-land.  On those systems,  we either get the `PDC_LINES` and `PDC_COLS` environment variables,  or default to 25 lines and 80 columns.  Which (looking at your screen shot and counting) is what you're getting : just the top 25x80 rectangle.

To fix this (and to detect screen resizes),  I think we'd need a good bit of Windows-specific code.  Some of it could probably be scraped from the WinCon port.  Since we have the WinCon port,  this is not currently high on my to-do list.
