### ISSUE TITLE
Makefiles broken: use reanamed README and HISTORY

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#13]
Just one thing I've recognized in the Makefiles:
- `win32/gccwin32.mak` uses `README.md` and `HISTORY.md`
- `win32a/gccwin32.mak` and `x11/Makefile.in` use `README` and `HISTORY` (these files aren' there anymore)
- all include `makedist.mif` which uses the new ones

Question (beside the obvious error and fix for the broken Makefiles):
Should all makefiles use the part of `win32/gccwin32.mak`? Maybe it should be removed completely?

**Comment by Bill-Gray** [comment]
Hi Simon,

    Thank you.  I've taken care of the easy one (adding .md to Makefile.in
and gccwin32.mak).

    I hadn't run a 'make dist',  and I don't know if such is likely to
happen now that we're on GitHub.  Still,  if the option exists,  it'd
be nice if it actually worked as advertised.

    It may indeed be time for gccwin32.mak to be removed.  One can (and I
do) use mingwin32.mak instead,  for both Win32 console and Win32a GDI
flavors,  cross-compiling from Linux or building natively under Windows,
in both cases with MinGW.  It used to be that I had to use gccwin32.mak
for building from Linux;  I eventually realized that the makefiles had
a great deal in common and could be combined.

    Incidentally,  if you run

cd win32a && make -f mingwin32.mak DLL=Y

    (i.e.,  just use mingwin32.mak instead of gccwin32.mak),  the unresolved
externals should go away.  The former includes the gdi32 and comdlg32
libraries that Win32a requires.  The latter does not.

    I don't have a Cygwin setup,  though,  and it may be that gccwin32.mak
is still needed for that.  It looks to me as if mingwin32.mak ought to
work with Cygwin,  but "looks as if" and "I've tested it" are not the same
thing.  If mingwin32.mak fails with Cygwin,  I'd hope we could fix the
failures and have one fewer makefile to deal with.  (Well,  two fewer:
we'd get rid of both the Win32 and Win32a versions.)

-- Bill

**Comment by GitMensch** [comment]
As written in the other thread:

mingwin32.mak in win32a does not work in general, something is missing for the DLL option:

    make -f mingwin32.mak DLL=Y
    make: *** No rule to make target `..\exp-base.def', needed by `pdcurses.def'.  Stop.

mingwin32.mak in win32a does not work when run from an msys shell (which I'd assume the standard option for mingw) as it uses copy and del, both not available as msys uses `sh`, not `cmd`.

I've changed the gccwin32.mak to include the linker options ` $(EXELIBS)` and `$(LIBSADDED)` and could built win32a with it. Is there any reason to not include these?

BTW: my cygwin setup doesn't build at all, see #14

**Comment by Bill-Gray** [comment]
Hi Simon,

On 2016-09-11 14:20, Simon Sobisch wrote:
> As written in the other thread:
>
> mingwin32.mak in win32a does not work in general, something is missing for the DLL option:
>
> |make -f mingwin32.mak DLL=Y make: *** No rule to make target `..\exp-base.def', needed
> by `pdcurses.def'. Stop.

    Seems a little weird.  Does that file not exist?  (It's part of the "standard"
PDCurses distribution;  there should be both a ..\exp-base.def and a ..\exp-wide.def.)

    It _may_ be related to this issue :

> mingwin32.mak in win32a does not work when run from an msys shell (which I'd assume the
> standard option for mingw) as it uses copy and del, both not available as msys uses
> |sh|, not |cmd|.

    I've not been using it from an MSYS shell.  I swapped some e-mails a while back with
a gent who was attempting to get it to build from MSYS.

    Am I correct that MSYS would expect ../exp-base.def rather than ..\exp-base.def?
i.e.,  forward rather than backward slash?

    If so,  the following revised makefile may do the trick (I don't actually have an
MSYS box on which to try it) :

http://www.projectpluto.com/mingnew.mak

    run as

make -f mingnew.mak MSYS=1 (other arguments)

    With MSYS=1,  path separators will be forward slashes,  and cp and rm will be used
instead of copy and del.  gcc will be invoked as the compiler.  One will be able to
use the same make file for cross-compiling from Linux,  or compiling from command.com,
_or_ (new and improved!) from MSYS.  And 'gccwin32.mak' can be retired.

**Comment by GitMensch** [comment]
>  Am I correct that MSYS would expect ../exp-base.def rather than ..\exp-base.def?

Yes, MSYS would expect this, CYGWIN, too.


Tested the new makefile with cygwin and MSYS (the output is the same):

~~~
simon@Soprano /tmp/install/PDCurses-master/win32a
$ make -f mingnew.mak clean   # testing just because it should work
*.o
/bin/sh: addch.o: command not found
make: *** [mingnew.mak:122: clean] Error 127

simon@Soprano /tmp/install/PDCurses-master/win32a
$ make -f mingnew.mak MSYS=1 clean   # shouldn't make only try to remove files that are existing?
rm *.o
rm *.exe
rm: cannot remove '*.exe': No such file or directory
make: [mingnew.mak:123: clean] Error 1 (ignored)
rm *.dll
rm: cannot remove '*.dll': No such file or directory
make: [mingnew.mak:124: clean] Error 1 (ignored)
rm *.def
rm: cannot remove '*.def': No such file or directory
make: [mingnew.mak:125: clean] Error 1 (ignored)
rm *.a
rm: cannot remove '*.a': No such file or directory
make: [mingnew.mak:126: clean] Error 1 (ignored)

simon@Soprano /tmp/install/PDCurses-master/win32a
$ make -f mingnew.mak
make: *** No rule to make target '..DELETE', needed by 'pdcclip.o'.  Stop.
~~~

Normal make starts but results in an error, see #14.

Testing the new makefile with MSYS as it should be used `make -f mingnew.mak MSYS=1` works.

There shouldn't be any need for setting MSYS on command line. I suggest to check if `pwd` works, if yes, use "unix" mode, otherwise the windows mode.

~~~

**Comment by GitMensch** [comment]
From GNU's makefile docs: using `pwd` is fine. There was another suggestion there: use the build-in `findstr`. Sample from the docs:

~~~
ifneq (,$(findstring t,$(MAKEFLAGS)))
        +touch archive.a
        +ranlib -t archive.a
else
        ranlib archive.a
endif
~~~

In our case we'd get the output of `pwd` (if pwd isn't available don't set the test string at all) and check the teststring for a `/`, if we find one it is very clear that we can use linux mode.

**Comment by Bill-Gray** [comment]
I've done a bit of searching on how to create GNU makefiles that will
work on Windows,  Cygwin,  Linux,  etc. without going through Autotools.
Use of 'uname' was widely suggested.  On Windows,  this will either fail,
tell you that you're under Cygwin,  or _maybe_ tell you you're under Windows
(Windows versions of uname do exist).  The makefile for Git provides some
examples :

https://git.kernel.org/cgit/git/git.git/tree/Makefile?id=c965c029330b1f81cc107c5d829e7fd79c61d8ea

Seems as if this may work.  You'll see that they combine uname output with
findstring to do things such as

uname_S := $(shell sh -c 'uname -s 2>/dev/null || echo not')
....
ifneq (,$(findstring CYGWIN,$(uname_S)))
    (do stuff)

i.e.,  findstring is used just to check if CYGWIN is part of the system's
name.

So I think you've got us on the right road here:  it should be possible to
detect if we're cross-compiling from Linux (or other Unix-like system),  or
Cygwin,  or from cmd.com in Windows,  and to apply the appropriate flags.
(Which I appreciate learning about;  I've makefiles in some other projects
suffering from similar issues.)

**Comment by GitMensch** [comment]
Hi Bill, any progress here?

**Comment by Bill-Gray** [comment]
Hi Simon,

   I think we might be there.  If not,  we should be getting close.

   I've posted an update to

http://www.projectpluto.com/mingnew.mak

   This applies the lessons learned from the above link to the Git makefile (essentially,  an exercise in creating a cross-platform makefile without resorting to Autotools/Autoconf.)  The current logic in the file is:  if 'uname -s' returns nothing,  assume we're in command.com or cmd.exe on a Windows box;  use del/copy/type and backslashes as path separators.  If uname -s returns a string containing CYGWIN,  assume we're on a Cygwin box;  use rm/cp/cat and forward slashes.  In both cases,  we're really on a Windows box,  and ON_WINDOWS is defined.

   If _neither_ of those things happen,  we have the third case:  we're on a Linux or *BSD or OS/X box,  cross-compiling with MinGW.  For these,  set an appropriate prefix to gcc,  depending on whether we're dealing with 32-bit or 64-bit code.

   About the only change I had to make relative to the Git makefile logic (aside from extracting only the bits that appear relevant for us) was to handle the non-Cygwin Windows case.  'uname' doesn't exist in that situation,  and one gets an error message and uname_S is set to blank.

   I've verified that this works on non-Cygwin Windows and for the cross-compile.  I think it'll work with Cygwin,  based solely on looking at gccwin.mak... please let me know what you find!

**Comment by Bill-Gray** [comment]
Haven't heard anything on this front since last September,  but I think the various fixes we've made (some committed today) have gotten Cygwin builds to work correctly,  fixing this and other issues.
