### ISSUE TITLE
No blinks in win32a

### ISSUE THREAD

**Issue by BigRedEye** [Bill-Gray/PDCurses#16]
Hi!
Here http://www.projectpluto.com/win32a.htm i see that win32a flavour can display blinking text, but for example `addch((int)'a' | A_BLINK);` displays 'a' on a constant background. Is it a bug?

**Comment by Bill-Gray** [comment]
On 2016-09-12 17:42, BigRedEye wrote:
> Hi!
> Here http://www.projectpluto.com/win32a.htm i see that win32a flavour can display
> blinking text, but for example |addch((int)'a' | A_BLINK);| displays 'a' on a constant
> background. Is it a bug?

    Try calling

PDC_set_blink( TRUE);

    See comments starting at line 65 in

https://github.com/Bill-Gray/PDCurses/blob/master/win32a/pdcsetsc.c

    This will get "real" blinking in Win32a and X11.  I think it might
work in DOS and OS/2.

-- Bill

**Comment by BigRedEye** [comment]
Thanks
