### ISSUE TITLE
Suspicious code in pdcscrn.c

### ISSUE THREAD

**Issue by pedro-w** [Bill-Gray/PDCurses#17]
Looking at pdcscrn.c:2348 I think maybe the parentheses are misplaced:
~~~~
        PDC_argc = argc;
        PDC_argv = (char **)calloc( argc + 1, sizeof( char *));
        for( i = 0; i < argc; i++)
        {
            PDC_argv[i] = (char *)malloc( strlen( argv[i] + 1));  // HERE!!
            strcpy( PDC_argv[i], argv[i]);
        }
~~~~
Should be `malloc( strlen( argv[i]) + 1)`
Could you check? Thanks.

**Comment by Bill-Gray** [comment]
OUCH!  That's downright embarrassing (to me;  I wrote that code).
Especially since valgrind should have caught that issue.  Thanks for
mentioning it;  I've fixed it.

    It may not have been caught before simply because that code is only
executed if one calls Xinitscr() with non-null arguments.  Xinitscr(0,NULL)
or initscr() will skip that code.
