### ISSUE TITLE
Include Laura Michaels' SDL2 port

### ISSUE THREAD

**Issue by rgson** [Bill-Gray/PDCurses#19]
The old pre-2.0 versions of SDL have been deprecated for some time now. Inclusion of Laura Michael's SDL2 port would be helpful to support migration to the newer version.

I was recently in touch with Laura Michaels about her port and received her patch. While I can simply use it as-is, patching an old version makes updating rather inconvenient and essentially locks me into an outdated version of PDCurses. Merging it here would greatly simplify the update process in the future while also making it available to anyone else with an interest in SDL2.

I'm opening this issue mostly as a way to probe for interest and information regarding this before spending any time on it. If there is interest in merging it, I'll start working on an actual pull request to do so.

Seeing as her TTF support backport for SDL was merged in commit 2e7d5ce176aae0dd24ab10e960cbe694d44aeae3, I'm wondering why the SDL2 support was left out. My guess is that it violates the guidelines set in `IMPLEMNT.md` by modifying another port (i.e. SDL1). Is that correct? Are there any other reasons for excluding the port?

**Comment by Bill-Gray** [comment]
Hmmm... I'm not especially knowledgeable about SDL.  Is there a good reason to have both SDL1 and SDL2 versions going?  Or should we just "move on" and drop SDL1?

I've not actually seen Laura's SDL2 patch.  If it's not huge,  I could imagine modifying the existing SDL1 code with #ifdefs so that one could do,  say,  'make SDL2=Y'.

I'm not too concerned about the guidelines about modifying another port.  As you may have seen,  this fork ran roughshod over all other ports and over 'curses.h'.  William McBrine is considerably more conservative in such matters.  So be warned:  any SDL2 work you do will probably get pulled into this fork,  but may never make it into "mainstream",  official PDCurses.  (I am currently working under the assumption that this fork is a for-real fork,  unlikely to ever be pulled into mainstream PDCurses.)

**Comment by rgson** [comment]
To be honest, I'm not especially knowledgeable about SDL either. From my understanding, SDL2 is the preferred way to go for new projects and for projects where migration is possible. However, since SDL2 has several breaking API changes, the transitional process is slow. If there is no clear reason for dropping SDL1 support then I'd probably keep it around for a while longer. If a situation arises where it's maintenance becomes an issue, then that would be a good time to drop it.

Regarding `#ifdef`s, Laura's patch actually does just that. It uses `ifeq ($(SDL),2)` in the Makefile to select the correct flags and `#if [SDL_VERSION_ATLEAST](https://wiki.libsdl.org/SDL_VERSION_ATLEAST)(2, 0, 0)` to select the correct pieces of code.

**Comment by rgson** [comment]
To be honest, I'm not especially knowledgeable about SDL either. From my understanding, SDL2 is the preferred way to go for new projects and for projects where migration is possible. However, since SDL2 has several breaking API changes, the transitional process is slow. If there is no clear reason for dropping SDL1 support then I'd probably keep it around for a while longer. If a situation arises where it's maintenance becomes an issue, then that would be a good time to drop it.

Regarding `#ifdef`s, Laura's patch actually does just that. It uses `ifeq ($(SDL),2)` in the Makefile to select the correct flags and `#if SDL_VERSION_ATLEAST(2, 0, 0)` (a macro provided by SDL) to select the correct pieces of code.

When it comes to the different forks, I actually found this fork through the pull request on wmcbrine/PDCurses. While it would of course be preferable to have the port in both forks, the lack of activity in the original repository is discouraging. With pull requests sitting around for over a year without response, it seems the chances of getting anything incorporated there is currently slim to none.

**Comment by Bill-Gray** [comment]
On 2016-11-08 04:28, Robin Gustafsson wrote:
> To be honest, I'm not especially knowledgeable about SDL either. From my
> understanding, SDL2 is the preferred way to go for new projects and for
> projects where migration is possible. However, since SDL2 has several
> breaking API changes, the transitional process is slow.

    Might not be that bad,  for us.  I educated myself a little at

https://wiki.libsdl.org/MigrationGuide

    While there's a fair bit to do,  none of it looks like rocket surgery.
And it sounds as if we can just use Laura's patch.  Which I don't see
on wmcbrine/PDCurses... just the SDL 1.2 patch for TTF fonts so one can
have a wide-character version.  (wmcbrine pulled that patch,  and it's
in my version as well.)

    I know Laura was running into some odd issues with wide-character
input and SDL 2.0,  which may have deterred her from submitting the
patch.  However,  I could imagine us doing things in two stages:  first,
moving to SDL 2.0,  and second,  getting a wide-character version to work.
(Actually,  I'd guess one could do it the other way around.  But the
reverse order would involve at least slightly more work;  we'd have
both the 8-bit and wide-char versions to move over from 1.2 to 2.0.)

    Step 2 might be split into "get wide-char output to work" (which is,
I think,  relatively simple) and then "get wide-char keyboard input to
work",  which sounds as if it may present trouble.

-- Bill

**Comment by rgson** [comment]
Sounds good!

I'll start by looking closer at Laura's patch and try to verify the issue you mentioned with wide-character input.

Once I have set up an environment where the patched version seems to be working as intended, I'll attempt to move the changes over to a more recent version of PDCurses. The patch was made for version 3.4 (commit 6909c66) which is currently 148 commits behind `master` in this fork, so there will likely be some complications along the way.

Assuming that works out OK, any remaining issues could then be dealt with. If the wide-character input issue wasn't solved, then I guess that should be fixed at this point.
