### ISSUE TITLE
Numeric keypad in Win32a

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCurses#22]
(Reported to me by Mário Montes and verified on my machine)

Run 'testcurs' and do the input test,  and hit the /, *, +, -, or Enter keys on the numeric keypad.  You get PADSLASH and /,  and similar for the other keys:  two keys returned for one keyhit.  Same problem in SDL2.  Doesn't happen in X11,  DOS, or SDL1;  those flavors work correctly.

**Comment by Bill-Gray** [comment]
Fixed,  in an ugly way,  at

https://github.com/Bill-Gray/PDCurses/commit/d0f5dddd016ae8485903859eecdf7f4cce836c93

Not quite good enough for me to close this issue.

**Comment by GitMensch** [comment]
@Bill-Gray This Issue will get 2 years old after you've applied the "ugly" fix. If you want to work on this again please reopen, until then I close it as "merge from upstream", extending the new ports and handling the PR seem to be much more important.
