### ISSUE TITLE
Question: which version (if any) should build and work on the console?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#24]
... for building on GNU/Linux without x11.

Is there are port that should work or not?

**Comment by Bill-Gray** [comment]
Hi Simon,

    There's no port for the console,  in GNU/Linux or in *BSD.  The
only thing one can do there is use ncurses.

    I have several programs that can be compiled for either ncurses
or PDCurses (my software for determining asteroid orbits from observations,
for example).  It does mean the occasional #ifdef PDCURSES,  but it's
not (thus far,  at least) a major problem.

    For example,  ncurses lacks a some keyhit defines such as ALT_A,
CTL_DEL,  etc.,  resulting in my making a 'curs_lin.h' that is
#included only if PDCURSES is not defined :

https://github.com/Bill-Gray/find_orb/blob/master/curs_lin.h

    ncurses lacks the clipboard function found in PDCurses.  The mouse
interface is slightly different.  Obviously,  the various extensions
found in PDCurses -- "real" blinking and italic text and such -- don't
exist in the GNU/Linux console.

    As you may have seen,  I recently tackled the job of getting the
PDCurses demo programs to compile with ncurses.  It "mostly" works.
There are some weirdnesses,  in the wide-character ACS display and
elsewhere.  Some of that may require more changes to the demo programs.

-- Bill

**Comment by GitMensch** [comment]
Thank you for this feedback - in this case I don't have any chance to test PDCurses on the "exotic" machines as they all are console-only.

**Comment by GitMensch** [comment]
Would it be worth the effort to add a console-only port to PDCurses (= one for all) or is it good to stay with NCurses on the console?

BTW: as NCurses is in active development: please make sure to file bug reports if you stumble over them.

**Comment by Bill-Gray** [comment]
I can't come up with a really good reason for a console-only PDCurses.
I think it would require essentially duplicating ncurses,  a daunting
thought by itself (it has,  as I understand it,  a heck of a lot of
code dedicated to the various concepts of what a "console" might be.)
Seems like a better idea just to make the modest alterations in code
required to have it work with either PDCurses or ncurses.

    There _are_ some bits and pieces of ncurses that PDCurses lacks,
which have been requested from time to time.  The 'forms' and 'menus'
libraries jump to mind.  There are a bunch of minor ones,  such as
the 'thick' variants for box-drawing characters (WACS_T_ULCORNER,
etc.) which exist in ncurses but not (as yet) in PDCurses.

    In re NCurses bugs:  haven't found any yet that I can think of.
I'm reasonably sure that the issues I've seen in the demos,  for
example,  are just the sort of "ncurses doesn't do things exactly
the same way as PDCurses" issues that I've encountered elsewhere.
