### ISSUE TITLE
ALT+ENTER will cause the subsequent keystroke to get swallowed

### ISSUE THREAD

**Issue by clangen** [Bill-Gray/PDCurses#28]
If the user presses ALT+ENTER, the keystroke after will be swallowed. It seems to have something to do with this commit: https://github.com/Bill-Gray/PDCurses/commit/84db661934fb17b2eb1b8cdc1fde0f0c8f350760

I don't understand the inner workings of key handling enough to suggest an elegant solution, but I seem to be able to work around it by ALSO remembering the last keycode that was processed, i.e:

```
static bool key_already_handled = FALSE;
static int last_key_handled = 0; /* added this */
```

then...

```
if (wParam == VK_MULTIPLY || wParam == VK_DIVIDE
    || wParam == VK_ADD || wParam == VK_SUBTRACT
    || wParam == VK_RETURN) {
        last_key_handled = key;
        key_already_handled = TRUE; /* added this */
    }
}
```

and finally...

```
    case WM_CHAR:       /* _Don't_ add Shift-Tab;  it's handled elsewhere */
        if( wParam != 9 || !(GetKeyState( VK_SHIFT) & 0x8000))
            if( !key_already_handled || last_key_handled != (int)wParam ) /* modified this */
               add_key_to_queue( (int)wParam );
        key_already_handled = FALSE;
        last_key_handled = 0; /* added this */
        break;
```

However, (1) it feels dirty, and (2) I have a feeling it may re-introduce the original bug. I don't currently have a keyboard with a numpad handy to test it out.

**Comment by Bill-Gray** [comment]
Yup,  that's a bug... same misbehavior here,  in both 'newtest' and 'testcurs'.  Thanks for pointing this out.

Unfortunately,  the key-handling code has gathered a lot of barnacles,  to the point where the way it works is no longer all that obvious to me,  even though I wrote some of it (much was recycled from Win32 console,  as I recall.)  I'll give it a look-over... unfortunately,  it may be a while;  the "day job" is heating up a bit.

**Comment by GitMensch** [comment]
@Bill-Gray Do you see https://github.com/clangen/PDCurses/commit/a4a5ec776449d85db67b33fc0698b7761d478a0a fixing this and may merge + close this issue?

**Comment by Bill-Gray** [comment]
Figured it out.  Marking `key_already_handled = TRUE` is necessary for the pad-multiply, sub, div,  add,  and Enter keys... _unless_ Alt is held down.  It wasn't just Alt-Enter that was messed up;  it was Alt-all of those keys.  (Except Alt-Padplus,  which is used for Unicode entry and was handled elsewhere anyway.)
Hit any of those four Alt-Pad keys,  and `key_already_handled` was set to TRUE... but no extra character was sent to be ignored.  Instead,  the next key hit was ignored.
