### ISSUE TITLE
TUI

### ISSUE THREAD

**Issue by flypie** [Bill-Gray/PDCurses#41]
I stole a bit of code from TUI.c, weditstr function. I found a rather annoy problem, this only occurs on my release build in Visual Studio, but if I click in the test edit box an exception is thrown in the call to isprint(), this is to validate that the charter is printable. Hiting the pause key can do the same.

A quick fix was
            else if (c < KEY_OFFSET && isprint(c)) {

but some form of isprint for the very extend returns of wgetch might be useful.

**Comment by Bill-Gray** [comment]
Thanks for reporting this.  I _think_ I see what's going on here.

https://msdn.microsoft.com/en-us/library/ewx8s4kw.aspx

says that "...The behavior of isprint and _isprint_l is undefined if c is not EOF or in the range 0 through 0xFF, inclusive. When a debug CRT library is used and c is not one of these values, the functions raise an assertion."

It looks to me as if we ought to be using iswprint() (i.e.,  checking a wide character for printability).  Which would make that line something like the following.  We want to ignore anything between KEY_OFFSET and KEY_MAX.  (KEY_MIN = KEY_OFFSET + 1,  which seems a little odd to me.)  And then we want to check if iswprint() considers that character to be printable.  So we get:

else if( (c < KEY_OFFSET || c > KEY_MAX) && iswprint( c)) {

Without this,  if I switch to a Russian keyboard layout,  nothing shows up in the dialog box.  With it... well,  the characters are now accepted,  but rubbish from U+00 to U+FF appears,  not the actual Russian text.

But the above "fix" will (a) cause your crash to go away and (b) be quite sufficient as long as everybody using your software uses a Western European language,  or at least an alphabet contained in U+00 to U+FF.  I'll see what I can do about the other ~90% of the world.

**Comment by flypie** [comment]
Ta

**Comment by flypie** [comment]
Should possible be KEY_CODE_YES not KEY_OFFSET for compatibility with ncurses.

**Comment by flypie** [comment]
Ta
