### ISSUE TITLE
Bug in pnoutrefresh

### ISSUE THREAD

**Issue by pedro-w** [Bill-Gray/PDCurses#43]
Whilst debugging I came across [this code](https://github.com/Bill-Gray/PDCurses/blob/master/pdcurses/pad.c#L181)
```` c
    if (!w || !(w->_flags & (_PAD|_SUBPAD)) || (sy2 >= LINES) || (sy2 >= COLS))
        return ERR;
````
should be (I think)
```` c
    if (!w || !(w->_flags & (_PAD|_SUBPAD)) || (sy2 >= LINES) || (sx2 >= COLS))
        return ERR;
````

**Comment by Bill-Gray** [comment]
Thank you;  that looks like a definite bug to me,  too.  I've fixed it and pushed it.

[The same bug is in 'official' PDCurses](https://github.com/wmcbrine/PDCurses/blob/master/pdcurses/pad.c#L181);  we hadn't modified pdcurses/pad.c in this fork (until today).  @wmcbrine may want to make the same fix.

**Comment by pedro-w** [comment]
Thanks for fixing so quickly! I also left a comment on the sourceforge forum for the official PDcurses, but I wasn't sure if it was the correct place, as a lot of the other comments there seemed quite old.
