### ISSUE TITLE
win32a and references to win32 console

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#47]
From win32a\README.md:

>   Another option, "UTF8=Y", makes PDCurses ignore the system locale, and
  treat all narrow-character strings as UTF-8. This option has no effect
  unless WIDE=Y is also set. Use it to get around the poor support for
  UTF-8 in the Win32 console:
>
>        make -f mingwin32.mak WIDE=Y UTF8=Y

win32a doesn't use the  win32 console - is this reference obsolete or has this still a relevance?

**Comment by Bill-Gray** [comment]
I think it may be referring to the poor UTF-8 support in Win32 in general.

I could easily imagine somebody building their project against the Win32 console flavor,  and either including or leaving out UTF-8.  Then they'd like to link against Win32a (or UTF8) without having to recompile their code,  simply building that flavor of PDCurses with the same flags they used for Win32 console.  So I think the UTF8/non-UTF8 variants will stay with us.

**Comment by GitMensch** [comment]
OK, so maybe change the win32a\README.md to include your comments in the previous post.

In general it may be interesting to test win32 in PowerShell which seems to have full utf8 support in-built.

**Comment by Bill-Gray** [comment]
Just changed `win32a/README.md` to give a slightly better explanation of why it's inherited this option.

**Comment by GitMensch** [comment]
Perfect.
