### ISSUE TITLE
Do we miss some merges from wmcbrine?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#61]
Not sure but I *guess* there's still something in that is missing here, isn't it?
https://github.com/Bill-Gray/PDCurses/compare/master...wmcbrine:master

**Comment by Bill-Gray** [comment]
I think we're all set.  There have been cases where a bug fix popped up in wmcbrine/master and I added it by hand,  more or less,  to this fork.  I think that happened quite a bit when Laura Michaels provided fixes to allow TrueType fonts in SDL1,  for example.  But all merges/fixes/improvements found in wmcbrine/master have made their way into this fork.

**Comment by GitMensch** [comment]
Thank you for checking. The parts that are confusing are the "hand made" integrations which lead to both the original commiters not being in the commit log here (which means they don't get credit and if a question to this commit pops up later we likely can't ask the original author) and "This branch is 9 commits behind wmcbrine:master. "
