### ISSUE TITLE
The paste button prints debug output even in the released code

### ISSUE THREAD

**Issue by Lokathor** [Bill-Gray/PDCurses#62]
https://github.com/Bill-Gray/PDCurses/blob/master/win32a/pdckbd.c#L67

If you use the paste button it prints the ilen info and all the clipboard contents even in the released version. I hope this is not intentional.

**Comment by Bill-Gray** [comment]
Yup,  that's my mistake.  Thanks for pointing it out.  That _really_ shouldn't have slipped by me...   6dbc1996ef7f2129dbac169467749be321f64fb5 fixes this.
