### ISSUE TITLE
[MSVS 2015] v4.0.2 build issue

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [Bill-Gray/PDCurses#65]
PDCurses\win32\pdcscrn.c(396): error C2065: 'true': undeclared identifier
true is defined in as:  #define true EMIT WARNING C4005

**Comment by arves100** [comment]
#if defined(_MSC_VER) && _MSC_VER >= 1800   /* VS2013 and above can't build */
    is_nt = 1;    /* non-NT (Win9x/3.1/ME) targets anyway,  so always true */
#else

i think should work with this

**Comment by Bill-Gray** [comment]
Thanks to you both.  I've messed that up before,  but always got a compiler warning... dunno why that didn't happen this time.
