### ISSUE TITLE
Do you mind to rename win32 to wincon?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#79]
Mostly @Bill-Gray.

... following the change of @wmcbrine...
And what do you think about also changing win32a to wingui?

I'd do these adjustments but as this should be considered as "breaking change" I'd like to know your thoughts on this beforehand.

**Comment by GitMensch** [comment]
Wincon rename done with 367a5131528e4d1b91cdd7b23e50454d91ee4b02.
@Bill-Gray Do you want to rename win32a or keep the name?

**Comment by GitMensch** [comment]
Ping @Bill-Gray What do you think about renaming the original win32a to wingui (or to a different name, you may have a better idea)

**Comment by Bill-Gray** [comment]
Just did two things I should have done a while ago:
(1) A search for WinGUI turns up a few uses,  but nothing that I think would cause people to wonder which WinGUI you were talking about.  Can't say I really like the name,  but I can't muster a really strong argument against it.  And quite a few objected to the 'win32a' name,  even before William changed 'win32' to 'wincon'.
(2) A case-insensitive 'grep' for win32a in the current repository turned up a lot of instances,  but nothing too horrific.  Use of 'sed' made it a mostly automated search and replace.  So I went ahead and did it.

**Comment by GitMensch** [comment]
Closed with 6e28dcc and a8fb6d9
