### ISSUE TITLE
x11.c 'XKeycodeToKeysym' deprecated

### ISSUE THREAD

**Issue by jwinarske** [Bill-Gray/PDCurses#92]
PDCurses/x11/x11.c:1422:19: warning: 'XKeycodeToKeysym' is deprecated [-Wdeprecated-declarations]
PDCurses/x11/x11.c:1522:14: warning: 'XKeycodeToKeysym' is deprecated [-Wdeprecated-declarations]

Solutions are discussed here:
https://bugs.chromium.org/p/chromium/issues/detail?id=117210

The fix would require changes in:
x11/x11.c
x11/config.h.in
x11/configure.ac

**Comment by Bill-Gray** [comment]
Note that this only shows up when you configure with the --enable-debug flag.  I don't entirely see how to fix it (seems to be several replacement methods suggested),  but also don't see why anything but `x11/x11.c' would be affected?

**Comment by jwinarske** [comment]
X11.c requires a change like this:

Add:

```#include <X11/XKBlib.h>```

Change:

```XKeycodeToKeysym(display_, key_code, 0);```

to:

```XkbKeycodeToKeysym(display_, key_code, 0, 0);```

Then conditionalize in build file.  Maybe allow an override.  I believe the deprecation is security related.

**Comment by GitMensch** [comment]
Closed as the referenced code is not used any more.
@jwinarske I'd appreciate if you could recheck if something similar still comes up with the new version.
