### ISSUE TITLE
x11.c compilation error with PDCDEBUG defined

### ISSUE THREAD

**Issue by jwinarske** [Bill-Gray/PDCurses#93]
```
/home/joel/git/PDCurses/x11/x11.c:3129:22: error: too many arguments to function call, expected single argument 'msg', have 2 arguments
                     PDC_blink_state));
                     ^~~~~~~~~~~~~~~~~
/home/joel/git/PDCurses/x11/pdcx11.h:171:27: note: expanded from macro 'XC_LOG'
# define XC_LOG(x) XC_say x
                   ~~~~~~ ^
/home/joel/git/PDCurses/x11/pdcx11.h:170:1: note: 'XC_say' declared here
void XC_say(const char *msg);
^
1 error generated.

```
One solution:
```
if(PDC_blink_state)
{
    XC_LOG(("CURSES_DISPLAY_CURSOR received from child.  Vis. now: 1\n"));
}
else
{
    XC_LOG(("CURSES_DISPLAY_CURSOR received from child.  Vis. now: 0\n"));
}
```

**Comment by GitMensch** [comment]
If this is the only case where a printf style logging is done then your approach is the correct thing to do. If there would be reasonable more cases the definition of XC_say should be changed to take varargs.

Please decide what you'd like to see and create a PR fixing it this way.
Thank you (also for all of your other work)!

**Comment by jwinarske** [comment]
It's the only case with it.  I'll create a PR for the simple solution.  It will enable the build matrix for now. 
 We can always change it later as needed.

**Comment by GitMensch** [comment]
Thank you for your work on PDCurses.
Just a note: please use the format `work on #NN` or, when finishing the work `fix #NN` as this creates a direct reference to the issue tracker (and also auto-closes the issues when merging).
